# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e41330a965f9ca01670c3d00a47c6272837b058bcce6101b3d4811cb6bf305f871abef8cd16926d138438dd316214956652a41fe3f97c133adec04d1b6203db7

test:
  secret_key_base: a19930c378e50448a5555fc982d6049c1b9be5de8e16f331fb6e3a2b12dc82f6c69444aab37a976cb96799fe32e1676defee2048a8498768c9957c573279f49f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
